# Jumpsuit
- type: loadout
  id: HeadofSecurityJumpsuit
  equipment: HeadofSecurityJumpsuit

- type: startingGear
  id: HeadofSecurityJumpsuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoS

- type: loadout
  id: HeadofSecurityJumpskirt
  equipment: HeadofSecurityJumpskirt

- type: startingGear
  id: HeadofSecurityJumpskirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoS

- type: loadout
  id: HeadofSecurityTurtleneck
  equipment: HeadofSecurityTurtleneck

- type: startingGear
  id: HeadofSecurityTurtleneck
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSAlt

- type: loadout
  id: HeadofSecurityTurtleneckSkirt
  equipment: HeadofSecurityTurtleneckSkirt

- type: startingGear
  id: HeadofSecurityTurtleneckSkirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoSAlt

- type: loadout
  id: HeadofSecurityFormalSuit
  equipment: HeadofSecurityFormalSuit

- type: startingGear
  id: HeadofSecurityFormalSuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitHosFormal

- type: loadout
  id: HeadofSecurityFormalSkirt
  equipment: HeadofSecurityFormalSkirt

- type: startingGear
  id: HeadofSecurityFormalSkirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHosFormal

#Blue - ERTAcdemy
- type: loadout
  id: HeadofSecurityJumpsuitBlue
  equipment: HeadofSecurityJumpsuitBlue

- type: startingGear
  id: HeadofSecurityJumpsuitBlue
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoS2Blue

- type: loadout
  id: HeadofSecurityJumpskirtBlue
  equipment: HeadofSecurityJumpskirtBlue

- type: startingGear
  id: HeadofSecurityJumpskirtBlue
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoS2Blue

- type: loadout
  id: HeadofSecurityTurtleneckBlue
  equipment: HeadofSecurityTurtleneckBlue

- type: startingGear
  id: HeadofSecurityTurtleneckBlue
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSAltBlue

- type: loadout
  id: HeadofSecurityTurtleneckSkirtBlue
  equipment: HeadofSecurityTurtleneckSkirtBlue

- type: startingGear
  id: HeadofSecurityTurtleneckSkirtBlue
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoSAltBlue

- type: loadout
  id: HeadofSecurityFormalSuitBlue
  equipment: HeadofSecurityFormalSuitBlue

- type: startingGear
  id: HeadofSecurityFormalSuitBlue
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSFormalBlue

- type: loadout
  id: HeadofSecurityFormalSkirtBlue
  equipment: HeadofSecurityFormalSkirtBlue

- type: startingGear
  id: HeadofSecurityFormalSkirtBlue
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoSFormalBlue

# Head
- type: loadout
  id: HeadofSecurityHead
  equipment: HeadofSecurityHead

- type: startingGear
  id: HeadofSecurityHead
  equipment:
    head: ClothingHeadHatHoshat

- type: loadout
  id: HeadofSecurityBeret
  equipment: HeadofSecurityBeret

- type: startingGear
  id: HeadofSecurityBeret
  equipment:
    head: ClothingHeadHatBeretHoS

# Neck
- type: loadout
  id: HeadofSecurityCloak
  equipment: HeadofSecurityCloak

- type: startingGear
  id: HeadofSecurityCloak
  equipment:
    neck: ClothingNeckCloakHos

- type: loadout
  id: HeadofSecurityMantle
  equipment: HeadofSecurityMantle

- type: startingGear
  id: HeadofSecurityMantle
  equipment:
    neck: ClothingNeckMantleHOS

# OuterClothing
- type: loadout
  id: HeadofSecurityCoat
  equipment: HeadofSecurityCoat

- type: startingGear
  id: HeadofSecurityCoat
  equipment:
    outerClothing: ClothingOuterCoatHoSTrench

- type: loadout
  id: HeadofSecurityWinterCoat
  equipment: HeadofSecurityWinterCoat

- type: startingGear
  id: HeadofSecurityWinterCoat
  equipment:
    outerClothing: ClothingOuterWinterHoS

# PDA
- type: loadout
  id: HoSPDA
  equipment: HoSPDA

- type: startingGear
  id: HoSPDA
  equipment:
    id: HoSPDA

- type: loadout
  id: HoSPDABlue
  equipment: HoSPDABlue

- type: startingGear
  id: HoSPDABlue
  equipment:
    id: HoSPDABlue
