- type: department
  id: CentralCommand
  description: department-CentralCommand-description
  color: "#13db0f"
  roles:

- type: department
  id: CentСomSpecialists
  description: department-CentСom-description
  color: "#35a41e"
  roles:
  - CentComConsultant
  - BlueShield

